zend_extension=xdebug

xdebug.mode=debug,develop
xdebug.start_with_request=yes

; 重要：Docker Desktop + WSL2 では host.docker.internal が基本
xdebug.client_host=host.docker.internal
xdebug.client_port=9003

; ログ（困った時だけONにして）
xdebug.log_level=0
; xdebug.log=/tmp/xdebug.log

; 任意：IDE側のサーバ名（VSCode/PhpStormで使うことがある）
xdebug.idekey=VSCODE
